version: "4.0"

services:
  #  api-service:
  #    container_name: api
  #    build: .
  #    restart: always
  #    ports:
  #      - $APP_LOCAL_PORT:$APP_DOCKER_PORT
  #    links:
  #      - api-database
  api-database:
    container_name: api-database
    image: mongo:5.0.14
    #hostname: srv-api-db - нет коннекта из явы
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    cpus: 1
    mem_limit: 1G
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    env_file: ./.env
    command: [--auth]
    volumes:
      - ./data:/data/db
      - ./dump:/dump
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    # Allow docker to connect to localhost
    #network_mode: "host"

volumes:
  mongodb_data:

networks:
  bridge:
