version: '3.8'

services:
  mongodb_container:
    container_name: mongodb_sandbox
    image: mongo:5.0.14
    hostname: my-mongodb
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    cpus: 1
    mem_limit: 1G
    mem_reservation: 1G
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    env_file: ./.env
    command: [--auth]
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data_container:

networks: